[package]
name = "mrc-to-tiff"
authors = ["Alexander Clausen <a.clausen@fz-juelich.de>"]
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.6.1", features = ["derive"] }
eframe = "0.33.3"
egui_plot = "0.34.1"
env_logger = "0.11.9"
indicatif = { version = "0.18.4", features = ["rayon"] }
indicatif-log-bridge = "0.2.3"
log = "0.4.29"
mrc = { features = ["std", "mmap"], version = "0.2.3" }
dm3dm4 = { git = "ssh://gitlab@iffgit.fz-juelich.de/clausen/dm3dm4-rs.git", rev="cbdddb8" }
rayon = "1.11.0"
rfd = "0.17.2"
thiserror = "2.0.18"
tiff-encoder = "0.3.2"
yoke = "0.8.2"
zerocopy = "0.8.48"
edit-distance = "2.2.2"
natord = "1.0.9"
pdqselect = "0.1.1"
rand = "0.10.1"


[[bin]]
name = "mrc-to-tiff"
path = "src/main.rs"

[[bin]]
name = "mrc-to-tiff-gui"
path = "src/gui.rs"

[lib]
name = "mrc_to_tiff"
path = "src/lib.rs"

[dev-dependencies]
criterion = "0.8.2"
rand = "0.10.1"

[[bench]]
name = "render_benchmarks"
harness = false
